# CNB pipeline: Use python:3.15-rc-bookworm, install requirements, run training
main:
  push:
    - docker:
        image: python:3.15-rc-bookworm
      stages:
        - pip install -r requirements.txt
        - cd my-tabformer
        - python main.py --do_train --mlm --field_ce --lm_type bert --field_hs 64 --data_type card --output_dir ./output