# CNB pipeline: Use python:3.15-rc-bookworm, install requirements, run training
main:
  push:
    - docker:
        image: python:3.15-rc-bookworm
      stages:
        - apt-get update && apt-get install -y tar gfortran build-essential libssl-dev libffi-dev libbz2-dev liblzma-dev libsqlite3-dev zlib1g-dev libreadline-dev libncurses5-dev libncursesw5-dev uuid-dev wget
        - pip install -r pip_freeze_output.txt
        - tar -xzf ./data/credit_card/transactions.tgz -C ./data/credit_card card_transaction.v1.csv
        - python main.py --do_train --mlm --field_ce --lm_type bert --field_hs 64 --data_type card --output_dir ./output